### ISSUE TITLE
run.bat启动时部分功能无法加载

### ISSUE THREAD

**Issue by Deetus** [HCskia/fu-Bot#2]
错误信息：failed to import "functions"
failed to import "music"
failed to import "maimaiDX"
舞萌相关功能无法使用

**Comment by HCskia** [comment]
有可能是库的引用问题，可以尝试用pycharm直接运行bot.py文件

**Comment by Deetus** [comment]
> 有可能是库的引用问题，可以尝试用pycharm直接运行bot.py文件

尝试使用pycharm运行，还是不行，报错结果一样，感觉似乎是music.py的导入出问题然后导致functions和maimaiDX都不能导入
<img width="392" alt="image" src="https://user-images.githubusercontent.com/31412013/227467541-33bdf95e-28b6-43b0-8e26-f42638fad046.png">
<img width="396" alt="image" src="https://user-images.githubusercontent.com/31412013/227467479-dc3fc933-f02d-4376-a35c-c358dc32c344.png">

**Comment by HCskia** [comment]
看了一下，确实music.py有问题，现在已经修复了，重新下载一下music.py替换掉之前的文件应该就可以正常使用了

**Comment by Deetus** [comment]
> 看了一下，确实music.py有问题，现在已经修复了，重新下载一下music.py替换掉之前的文件应该就可以正常使用了

运行是没问题了，不过b站解析和戳一戳的监听似乎还不太行

**Comment by HCskia** [comment]
戳一戳的话如果你用的是安卓手表协议，就无法收到戳一戳消息。用ipad协议测试时是正常的，b站解析有一点缺陷，过段时间我更新修复一下
